onEvent('item.registry', event => {
	//弹壳
	event.create('ctza:shell_case')
	//亚原子锭
	event.create('ctza:subatomic_ingot')
	//光辉板
	event.create('ctza:radiant_sheet')
		.glow(true)
	//光辉线圈
	event.create('ctza:radiant_coil')
		.glow(true)
	//永恒之石
	event.create('ctza:eternal_stone')
	//熔岩构件
	event.create('ctza:lava_mechanism')
	//熔岩构件(半成品)
	event.create('ctza:incomplete_lava_mechanism')
		.type('create:sequenced_assembly')
	//燃烧室核心
	event.create('ctza:burner_core')
	//磨制朱砂
	event.create('ctza:polished_cinnabar')
	//磨制磷灰石
	event.create('ctza:polished_apatite')
	//动力构件
	event.create('ctza:kinetic_mechanism')
	//动力构件(半成品)
	event.create('ctza:incomplete_kinetic_mechanism')
		.type('create:sequenced_assembly')
	//绝缘构件
	event.create('ctza:insulation_mechanism')
	//绝缘构件(半成品)
	event.create('ctza:incomplete_insulation_mechanism')
		.type('create:sequenced_assembly')
	//安山合金板
	event.create('ctza:andesit_sheet')
	//末影构件
	event.create('ctza:ender_mechanism')
	//末影构件(半成品)
	event.create('ctza:incomplete_ender_mechanism')
		.type('create:sequenced_assembly')
})