modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/Steam-Powered/issues"
[[mods]] #mandatory
modId = "steampowered" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Create: Steam Powered" #mandatory
authors = "[TeamMoeg] YueSha, khjxiaogu, goumo_g"
credits = "We appreciate MRH0 for his code on RPM-FE conversion logic which we adapted in Steam Powered"
description = '''
Expanding Create mod to the Steam Age
'''
[[dependencies.steampowered]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.steampowered]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.steampowered]]
    modId="create"
    mandatory=true
    versionRange="[v0.3.2d,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steampowered]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.16-0.2.3,1.16-0.3)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.steampowered]]
    modId="alloyed"
    mandatory=false
    versionRange="[1.16.5,)"
    ordering="AFTER"
    side="BOTH"
